# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.table_api import TableApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTableApi(unittest.TestCase):
    """TableApi unit test stubs"""

    def setUp(self):
        self.api = TableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_table_get(self):
        """Test case for table_get

        """
        pass

    def test_table_id_delete(self):
        """Test case for table_id_delete

        """
        pass

    def test_table_id_get(self):
        """Test case for table_id_get

        """
        pass

    def test_table_post(self):
        """Test case for table_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
