# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.booking_api import BookingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBookingApi(unittest.TestCase):
    """BookingApi unit test stubs"""

    def setUp(self):
        self.api = BookingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_booked_dates_get(self):
        """Test case for booked_dates_get

        """
        pass

    def test_booking_get(self):
        """Test case for booking_get

        """
        pass

    def test_booking_id_delete(self):
        """Test case for booking_id_delete

        """
        pass

    def test_booking_id_get(self):
        """Test case for booking_id_get

        """
        pass

    def test_booking_post(self):
        """Test case for booking_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
