# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_find_phone_get(self):
        """Test case for user_find_phone_get

        """
        pass

    def test_user_get(self):
        """Test case for user_get

        """
        pass

    def test_user_id_delete(self):
        """Test case for user_id_delete

        """
        pass

    def test_user_id_get(self):
        """Test case for user_id_get

        """
        pass

    def test_user_post(self):
        """Test case for user_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
